name: sgeop
channels:
  - conda-forge
dependencies:
  - python=3.12
  - esda>=2.6.0
  - geopandas>=1.0.1
  - libpysal>=4.12.1
  - momepy>=0.8.1
  - networkx>=3.3
  - numpy>=1.26.4
  - pandas>=2.2.3
  - scipy>=1.14.1
  - shapely>=2.0.6
  # testing
  - pre-commit
  - pyarrow>=17.0
  - pytest
  - pytest-cov
  - pytest-xdist
